name: Soaring Memories
favicon: null
layout_spectrum: 0.6624235576018691
typography_spectrum: 0.4719719688873738
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.48528733127750456
  lightness: 0.5665841198060662
  saturation: 0.1437756405211985
  rhythmicContrast: 0.23631950607523322
purpose: []
